language: python
python:
  - "2.7"
install:    'pip install --use-mirrors unittest2 '
before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.8.2.zip
  - unzip -q google_appengine_1.8.2.zip
  - export GAE_PATH=./google_appengine
  - python $TRAVIS_BUILD_DIR/buster/application/generate_keys.py
script: $TRAVIS_BUILD_DIR/runtests.py  $GAE_PATH $TRAVIS_BUILD_DIR/buster/tests/

